apiVersion: nodeops.k8s.preferred.jp/v1alpha1
kind: NodeOperation
metadata:
  name: tutorial1
spec:
  nodeName: "nodeops-tutorial-worker"
  jobTemplate:
    metadata:
      namespace: default
    spec:
      template:
        spec:
          containers:
            - name: operation
              image: busybox
              command: ["sh", "-c", "echo Do some operation for $TARGET_NODE && sleep 60 && echo Done"]
              env:
                - name: TARGET_NODE
                  valueFrom:
                    fieldRef:
                      fieldPath: "metadata.annotations['nodeops.k8s.preferred.jp/nodename']"
          restartPolicy: Never
