apiVersion: nodeops.k8s.preferred.jp/v1alpha1
kind: NodeRemediationRule
metadata:
  name: tutorial1
spec:
  nodeSelector:
    auto-remediation: ''
  template:
    spec:
      nodeOperationTemplateName: tutorial1
      rule:
        conditions:
        - type: Tutorial
          status: "True"
