apiVersion: nodeops.k8s.preferred.jp/v1alpha1
kind: NodeOperationTemplate
metadata:
  name: tutorial1
spec:
  template:
    metadata: {}
    spec: # NodeOperationSpec
      jobTemplate:
        metadata:
          namespace: default
        spec: # batchv1.JobSpec
          template:
            spec:
              containers:
                - name: operation
                  image: busybox
                  command: ["echo", "Do some operation here"]
              restartPolicy: Never
