# permissions for end users to view noderemediationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: noderemediationtemplate-viewer-role
rules:
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - noderemediationtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - noderemediationtemplates/status
  verbs:
  - get
