# permissions for end users to edit nodeoperations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeoperation-editor-role
rules:
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - nodeoperations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - nodeoperations/status
  verbs:
  - get
