# permissions for end users to view nodedisruptionbudgets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodedisruptionbudget-viewer-role
rules:
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - nodedisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - nodedisruptionbudgets/status
  verbs:
  - get
