# permissions for end users to view nodeoperationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeoperationtemplate-viewer-role
rules:
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - nodeoperationtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - nodeoperationtemplates/status
  verbs:
  - get
