# permissions for end users to view noderemediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: noderemediation-viewer-role
rules:
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - noderemediations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - noderemediations/status
  verbs:
  - get
