# permissions for end users to edit noderemediationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: noderemediationtemplate-editor-role
rules:
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - noderemediationtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - noderemediationtemplates/status
  verbs:
  - get
