apiVersion: nodeops.k8s.preferred.jp/v1alpha1
kind: NodeRemediationTemplate
metadata:
  name: noderemediationtemplate-sample
spec:
  nodeSelector:
    'kubernetes.io/os': 'linux'
  template:
    nodeOperationTemplateName: 'example1'
    rule:
      conditions:
      - type: 'type1'
        status: 'status2'
