# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/nodeops.k8s.preferred.jp_nodeoperations.yaml
- bases/nodeops.k8s.preferred.jp_nodedisruptionbudgets.yaml
- bases/nodeops.k8s.preferred.jp_nodeoperationtemplates.yaml
- bases/nodeops.k8s.preferred.jp_noderemediationtemplates.yaml
- bases/nodeops.k8s.preferred.jp_noderemediations.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_nodeoperations.yaml
#- patches/webhook_in_nodedisruptionbudgets.yaml
#- patches/webhook_in_nodeoperationtemplates.yaml
#- patches/webhook_in_noderemediationtemplates.yaml
#- patches/webhook_in_noderemediations.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_nodeoperations.yaml
#- patches/cainjection_in_nodedisruptionbudgets.yaml
#- patches/cainjection_in_nodeoperationtemplates.yaml
#- patches/cainjection_in_noderemediationtemplates.yaml
#- patches/cainjection_in_noderemediations.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
