name: CI

on:
  push:
    branches: [master]
    paths-ignore: ['**.md']
  pull_request:
    types: [opened, synchronize]
    paths-ignore: ['**.md']

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "1.22"
        check-latest: true
        cache: true
    - name: Initialize Go modules
      run: |
        go mod tidy
        go mod download
    - name: Install controller-gen
      run: |
        go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.13.0
    - name: Run tests
      run: make test

  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "1.22"
        check-latest: true
        cache: true
    - name: Initialize Go modules
      run: |
        go mod tidy
        go mod download
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: ghcr.io/${{ github.repository }}:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_STEP_LOG_MAX_SIZE=10485760
          BUILDKIT_STEP_LOG_MAX_SPEED=10485760
